-- NOT NULL constraint violation: Missing NAME
INSERT INTO STATION (STATION_CODE, CITY, STATE, ZIP, STREET, LATITUDE, LONGITUDE)
VALUES ('NYK', 'New York', 'NY', '10001', '1 Penn Plaza', 40.7505, -73.9936);

-- CHECK constraint violation: Invalid latitude/longitude/STATE
INSERT INTO STATION (STATION_CODE, NAME, CITY, STATE, ZIP, STREET, LATITUDE, LONGITUDE)
VALUES ('WAS', 'Union Station', 'Washington', 'ER', '20002', '50 Massachusetts Ave NE', 95.0000000, -185.0000000);

-- CHECK constraint violation (via trigger): Invalid PHONE/EMAIL format
INSERT INTO PASSENGER (PASSENGER_ID, NAME, EMAIL, PHONE, ADDRESS)
VALUES (3, 'Jane Smith', 'invalid_email', '123456789100', '789 Pine Ln');

-- NOT NULL constraint violation: Not Nullable ARRIVAL_TIME/DEPARTURE_TIME
INSERT INTO TICKET (TICKET_ID, PASSENGER_ID, DEPARTURE_TIME, CONFIRMATION_CODE)
VALUES (104, 2, null, null);

-- PRIMARY KEY constraint violation: Duplicate TICKET_ID
INSERT INTO TICKET (TICKET_ID, PASSENGER_ID, DEPARTURE_TIME, ARRIVAL_TIME, CONFIRMATION_CODE)
VALUES (101, 4, TIMESTAMP '2025-05-06 16:00:00', TIMESTAMP '2025-05-06 17:45:00', null);

-- CHECK constraint violation (via trigger): Invalid ROLE
INSERT INTO STAFF (STAFF_ID, L_NAME, F_NAME, EMAIL, PHONE, ROLE)
VALUES (203, 'Williams', 'Charlie', null, '5555556666', 'TEACHER');

-- FOREIGN KEY constraint violation: Invalid VEHICLE_ID
INSERT INTO STAFF (STAFF_ID, L_NAME, F_NAME, EMAIL, PHONE, VEHICLE_ID)
VALUES (206, 'Hall', 'Fiona', null, '5559990000', 99999);

-- FOREIGN KEY constraint violation: Invalid ASSIGNED_STATION_CODE
INSERT INTO STAFF (STAFF_ID, L_NAME, F_NAME, EMAIL, PHONE, ASSIGNED_STATION_CODE)
VALUES (207, 'Irwin', 'George', 'george@example.com', '5551234567', 'ZZZ');

-- PRIMARY KEY constraint violation: Duplicate STAFF_ID
INSERT INTO STAFF (STAFF_ID, L_NAME, F_NAME, EMAIL, PHONE)
VALUES (2, 'Another Staff', 'Person', NULL, '1119992222');

-- UNIQUE constraint violation: Duplicate VIN
INSERT INTO VEHICLE (VEHICLE_ID, VEHICLE_TYPE, MODEL, NAME, AGE, VIN)
VALUES (304, 1, 'Superliner', 'Long Haul Train', TIMESTAMP '2030-03-01 00:00:00', '2HGES26742H527362');

-- FOREIGN KEY constraint violation: Invalid VEHICLE_ID
INSERT INTO ROUTE (ROUTE_ID, NAME, ORIGIN_ID, DEST_ID, VEHICLE_ID, VEHICLE_TYPE, DURATION_MINUTES, DISTANCE_MILES)
VALUES (404, 'Empire', 'NYK', 'ALB', 9999, 1, 150, 140);

-- CHECK constraint violation (via trigger): Invalid DISTANCE_MILES/DURATION_MINUTES
INSERT INTO ROUTE (ROUTE_ID, NAME, ORIGIN_ID, DEST_ID, VEHICLE_ID, VEHICLE_TYPE, DURATION_MINUTES, DISTANCE_MILES)
VALUES (406, 'Palmetto', 'WAS', 'SAV', 5, 1, -123, -50);

-- PRIMARY KEY constraint violation: Duplicate ROUTE_ID
INSERT INTO ROUTE (ROUTE_ID, NAME, ORIGIN_ID, DEST_ID, VEHICLE_ID, VEHICLE_TYPE, DURATION_MINUTES, DISTANCE_MILES)
VALUES (401, 'Another Route', 'BOS', 'NYK', 6, 1, 250, 220);

-- NOT NULL constraint violation: Missing ROUTE_ID
INSERT INTO SCHEDULE (SCHEDULE_ID, DEPARTURE_TIME, ARRIVAL_TIME, DAYS_OF_WEEK)
VALUES (501, TIMESTAMP '2025-05-10 08:00:00', TIMESTAMP '2025-05-10 10:00:00', 62);

-- CHECK constraint violation (via trigger): ARRIVAL_TIME before DEPARTURE_TIME
INSERT INTO SCHEDULE (SCHEDULE_ID, ROUTE_ID, DEPARTURE_TIME, ARRIVAL_TIME, DAYS_OF_WEEK)
VALUES (503, 1, TIMESTAMP '2025-05-12 16:00:00', TIMESTAMP '2025-05-12 15:00:00', 127);

-- FOREIGN KEY constraint violation: Invalid SCHEDULE_ID
INSERT INTO ROUTE_TICKET (ROUTE_TICKET_ID, ORDER_ID, TICKET_ID, SCHEDULE_ID)
VALUES (603, 2, 102, 9999999);