DROP TABLE ROUTE PURGE;

DROP TABLE SCHEDULE PURGE;

DROP TABLE TICKET PURGE;

DROP TABLE VEHICLE PURGE;

DROP TABLE STAFF PURGE;

DROP TABLE STATION PURGE;

DROP TABLE ROUTE_TICKET PURGE;

DROP TABLE PASSENGER PURGE;