-- indexes for querying
CREATE INDEX IDX_STATION_CITY ON STATION(CITY);
CREATE INDEX IDX_STATION_STATE ON STATION(STATE);

CREATE INDEX IDX_SCHEDULE_ARRIVAL ON SCHEDULE(ARRIVAL_TIME);
CREATE INDEX IDX_SCHEDULE_DEPARTURE ON SCHEDULE(DEPARTURE_TIME);

CREATE INDEX IDX_PAYMENT_DATE ON PAYMENT(PAYMENT_DATE);

CREATE INDEX IDX_VEHICLE_TYPE ON VEHICLE(VEHICLE_TYPE);

CREATE INDEX IDX_ROUTE_ORIGIN_DEST ON ROUTE(ORIGIN_ID, DEST_ID); -- index for both origin and destination

-- indexes for foreign keys
CREATE INDEX IDX_ROUTE_ORIGIN ON ROUTE(ORIGIN_ID);
CREATE INDEX IDX_ROUTE_DEST ON ROUTE(DEST_ID);
CREATE INDEX IDX_ROUTE_VEHICLE ON ROUTE(VEHICLE_ID);

CREATE INDEX IDX_TICKET_PASSENGER ON TICKET(PASSENGER_ID);

CREATE INDEX IDX_SCHEDULE_ROUTE ON SCHEDULE(ROUTE_ID);

CREATE INDEX IDX_STAFF_STATION ON STAFF(ASSIGNED_STATION_CODE);

CREATE INDEX IDX_ROUTE_TICKET ON ROUTE_TICKET(TICKET_ID);