CREATE TABLE STATION (
    STATION_CODE VARCHAR2(10) PRIMARY KEY,
    NAME         VARCHAR2(50) NOT NULL,
    CITY         VARCHAR2(25) NOT NULL,
    STATE        VARCHAR2(2) NOT NULL,
    ZIP          VARCHAR2(20) NOT NULL,
    STREET       VARCHAR2(20) NOT NULL,
    LATITUDE     NUMBER(10, 7) NOT NULL,
    LONGITUDE    NUMBER(10, 7) NOT NULL
);

CREATE TABLE PASSENGER (
    PASSENGER_ID INTEGER PRIMARY KEY,
    NAME         VARCHAR2(50) NOT NULL,
    EMAIL        VARCHAR2(100) NOT NULL UNIQUE,
    PHONE        VARCHAR2(15) NOT NULL UNIQUE,
    ADDRESS      VARCHAR2(255) NOT NULL
);

CREATE TABLE TICKET (
    TICKET_ID         INTEGER PRIMARY KEY,
    PASSENGER_ID      INTEGER NOT NULL,
    DEPARTURE_TIME    TIMESTAMP NOT NULL,
    ARRIVAL_TIME      TIMESTAMP NOT NULL,
    CONFIRMATION_CODE VARCHAR2(50) NOT NULL UNIQUE,
    CONSTRAINT FK_TICKET_PASSENGER FOREIGN KEY ( PASSENGER_ID )
        REFERENCES PASSENGER ( PASSENGER_ID )
);

CREATE TABLE STAFF (
    STAFF_ID              INTEGER PRIMARY KEY,
    L_NAME                VARCHAR(25) NOT NULL,
    F_NAME                VARCHAR(25) NOT NULL,
    EMAIL                 VARCHAR(100) NOT NULL UNIQUE,
    PHONE                 VARCHAR(15) NOT NULL UNIQUE,
    ROLE                  VARCHAR(50),-- CONDUCTOR, DRIVER, CLERK
    VEHICLE_ID            INTEGER,
    ASSIGNED_STATION_CODE VARCHAR2(10),
    CONSTRAINT FK_STAFF_VEHICLE FOREIGN KEY ( VEHICLE_ID )
        REFERENCES VEHICLE ( VEHICLE_ID ),
    CONSTRAINT FK_STAFF_STATION FOREIGN KEY ( ASSIGNED_STATION_CODE )
        REFERENCES STATION ( STATION_CODE )
);

CREATE TABLE VEHICLE (
    VEHICLE_ID   INTEGER PRIMARY KEY,
    VEHICLE_TYPE NUMBER(1) NOT NULL,-- 1 FOR TRAIN, 0 FOR BUS
    MODEL        VARCHAR2(50) NOT NULL,
    NAME         VARCHAR2(100) NOT NULL,
    AGE          TIMESTAMP NOT NULL,
    VIN          VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE ROUTE (
    ROUTE_ID         INTEGER PRIMARY KEY,
    NAME             VARCHAR2(50) NOT NULL,
    ORIGIN_ID        VARCHAR2(10),
    DEST_ID          VARCHAR2(10),
    VEHICLE_ID       INTEGER NOT NULL,
    VEHICLE_TYPE     NUMBER(1) NOT NULL,-- 1 FOR TRAIN, 0 FOR BUS
    DURATION_MINUTES INTEGER NOT NULL,
    DISTANCE_MILES   INTEGER NOT NULL,
    CONSTRAINT FK_ROUTE_VEHICLE FOREIGN KEY ( VEHICLE_ID )
        REFERENCES VEHICLE ( VEHICLE_ID ),
    CONSTRAINT FK_ROUTE_ORIGIN FOREIGN KEY ( ORIGIN_ID )
        REFERENCES STATION ( STATION_CODE ),
    CONSTRAINT FK_ROUTE_DEST FOREIGN KEY ( DEST_ID )
        REFERENCES STATION ( STATION_CODE )
);

CREATE TABLE SCHEDULE (
    SCHEDULE_ID    INTEGER PRIMARY KEY,
    ROUTE_ID       INTEGER NOT NULL,
    DEPARTURE_TIME TIMESTAMP,
    ARRIVAL_TIME   TIMESTAMP,
    DAYS_OF_WEEK   NUMBER(3),
     -- MON|TUE|WED|THUR|FRI|SAT|SUN using bit masks up to 128
    CONSTRAINT FK_SCHEDULE_ROUTE FOREIGN KEY ( ROUTE_ID )
        REFERENCES ROUTE ( ROUTE_ID )
);

CREATE TABLE ROUTE_TICKET (
    ROUTE_TICKET_ID INTEGER PRIMARY KEY,
    ORDER_ID        INTEGER NOT NULL,
    TICKET_ID       INTEGER NOT NULL,
    SCHEDULE_ID     INTEGER NOT NULL,
    CONSTRAINT FK_ROUTE_TICKET FOREIGN KEY ( TICKET_ID )
        REFERENCES TICKET ( TICKET_ID ),
    CONSTRAINT FK_TICKET_SCHEDULE FOREIGN KEY ( SCHEDULE_ID )
        REFERENCES SCHEDULE ( SCHEDULE_ID )
);