-- STATION table
UPDATE STATION
SET
    ZIP = '33605'
WHERE
    STATION_CODE = 'TPA';

UPDATE STATION
SET
    NAME = 'Orlando Regional Station',
    STREET = '1500 Sligh Blvd'
WHERE
    CITY = 'Orlando';

-- PASSENGER table
UPDATE PASSENGER
SET
    PHONE = '4342101934'
WHERE
    PASSENGER_ID = 1;

UPDATE PASSENGER
SET
    ADDRESS = 'Updated Address, Some City, Some State - 12345, USA'
WHERE
    EMAIL LIKE '%@outlook.com';

-- TICKET table
UPDATE TICKET
SET
    CONFIRMATION_CODE = 'ABC-123-DEF'
WHERE
    TICKET_ID = 101;

UPDATE TICKET
SET
    ARRIVAL_TIME = DEPARTURE_TIME + INTERVAL '4' HOUR
WHERE
    PASSENGER_ID IN (
        SELECT
            PASSENGER_ID
        FROM
            PASSENGER
        WHERE
            NAME LIKE 'Alan%'
    );

-- STAFF table
UPDATE STAFF
SET
    ROLE = 'Driver',
    VEHICLE_ID = 305
WHERE
    STAFF_ID = 3;

UPDATE STAFF
SET
    ROLE = 'Clerk',
    VEHICLE_ID = NULL
WHERE
    STAFF_ID = 6;

-- VEHICLE table
UPDATE VEHICLE
SET
    NAME = 'Silver Comet 1'
WHERE
    VEHICLE_ID = 301;

UPDATE VEHICLE
SET
    AGE = AGE + INTERVAL '1' YEAR
WHERE
        VEHICLE_TYPE = 1
    AND MODEL LIKE '%Charger%';

-- ROUTE table
UPDATE ROUTE
SET
    DURATION_MINUTES = 250
WHERE
    ROUTE_ID = 401;

UPDATE ROUTE
SET
    DISTANCE_MILES = DISTANCE_MILES + 10
WHERE
        ORIGIN_ID = 'ORL'
    AND DEST_ID = 'MIA';

-- SCHEDULE table
UPDATE SCHEDULE
SET
    DEPARTURE_TIME = TO_TIMESTAMP('2025-04-01 08:30:00', 'YYYY-MM-DD HH24:MI:SS')
WHERE
    SCHEDULE_ID = 501;

UPDATE SCHEDULE
SET
    ARRIVAL_TIME = DEPARTURE_TIME + INTERVAL '3' HOUR + INTERVAL '45' MINUTE
WHERE
    ROUTE_ID IN (
        SELECT
            ROUTE_ID
        FROM
            ROUTE
        WHERE
            NAME LIKE 'Miami%'
    );